function h = compute_h(in1,in2,Iz_1,l,m,r,b_1,b_2,g)
%COMPUTE_H
%    H = COMPUTE_H(IN1,IN2,Iz_1,L,M,R,B_1,B_2,G)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    30-Apr-2026 22:13:02

q_2 = in1(2,:);
v_1 = in2(1,:);
v_2 = in2(2,:);
t2 = sin(q_2);
t3 = l.^2;
t4 = q_2.*2.0;
t5 = sin(t4);
h = v_1.*(b_1+(m.*t3.*t5.*v_2)./2.0)+(l.*m.*v_2.*(l.*t5.*v_1-r.*t2.*v_2.*2.0))./2.0-(r.*cos(q_2).*(b_2.*v_2+g.*l.*m.*t2-(m.*t3.*t5.*v_1.^2)./2.0))./l;
end
