function Meff = compute_Meff(in1,Iz_1,l,m,r)
%compute_Meff
%    Meff = compute_Meff(IN1,Iz_1,L,M,R)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    30-Apr-2026 22:13:02

q_2 = in1(2,:);
t2 = cos(q_2);
t3 = l.^2;
t4 = r.^2;
t5 = t2.^2;
Meff = Iz_1+m.*t3+m.*t4-m.*t3.*t5-m.*t4.*t5;
end
