function xdot = RRpendulum_dynamics_ct(in1,tau_1)
%RRpendulum_dynamics_ct
%    XDOT = RRpendulum_dynamics_ct(IN1,TAU_1)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    25-Mar-2026 10:52:12

%Continuous-time dynamics for RR pendulum (auto-generated).
q_2 = in1(3,:);
v_1 = in1(2,:);
v_2 = in1(4,:);
t2 = cos(q_2);
t3 = sin(q_2);
t4 = q_2.*2.0;
t5 = v_1.^2;
t6 = v_2.^2;
t7 = t2.^2;
t8 = sin(t4);
t9 = t3.^3;
t10 = t7.*1.093806e-3;
t11 = t10-1.123806e-3;
t12 = 1.0./t11;
et1 = t3.*9.919086677323361e-6+t9.*2.521293065461586e-5+v_2.*3.371418e-8-t5.*t8.*4.531822990002e-7;
et2 = t6.*t8.*1.1585266581042e-7+t2.*tau_1.*4.813578e-4-t2.*v_1.*4.813578e-8-t7.*v_2.*2.4195402e-8+t2.^3.*t3.*t5.*6.5046386437956e-7-t3.*v_1.*v_2.*7.7644303178904e-7;
et3 = t9.*v_1.*v_2.*7.7644303178904e-7;
mt1 = [v_1;t12.*(t8.*2.360253734685e-3+tau_1.*(2.53e+2./1.0e+3)-v_1.*2.53e-5+t3.*t6.*1.217835234e-4+t2.*v_2.*4.53e-6-t5.*(t3-t9).*1.217835234e-4-t8.*v_1.*v_2.*2.040478902e-4).*(-1.0e+3./2.53e+2);v_2];
mt2 = [t12.*(et1+et2+et3).*1.239905003438257e+3];
xdot = [mt1;mt2];
end
