function Iz1tot = RRpendulum_totalIz1(in1,Iz_1,m,r,l)
%RRpendulum_totalIz1
%    Iz1tot = RRpendulum_totalIz1(IN1,Iz_1,M,R,L)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    24-Feb-2026 17:53:22

%Calculate total inertia around Iz1 axis for certain pose (auto-generated).
q_1 = in1(1,:);
q_2 = in1(2,:);
t2 = cos(q_1);
t3 = sin(q_1);
t4 = sin(q_2);
Iz1tot = Iz_1+m.*((r.*t3+l.*t2.*t4).^2+(r.*t2-l.*t3.*t4).^2);
end
